#!/bin/sh

case "$1" in
    start)
        echo "Starting PPPwn..."
        network-detector &
        sleep 5
        pppwn-runner &
        ;;
    stop)
        killall pppwn-runner network-detector 2>/dev/null
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac